In [1]:
import pandas as pd

In [2]:
import os
print(os.getcwd())

/Users/sivapalandineshkumar/Desktop/obesity_project/notebooks

In [3]:
GROUP1 = pd.read_csv("../data/FOOD-DATA-GROUP1.csv")
GROUP2 = pd.read_csv("../data/FOOD-DATA-GROUP2.csv")
GROUP3 = pd.read_csv("../data/FOOD-DATA-GROUP3.csv")
GROUP4 = pd.read_csv("../data/FOOD-DATA-GROUP4.csv")
GROUP5 = pd.read_csv("../data/FOOD-DATA-GROUP5.csv")

In [4]:
data = pd.concat(
    [GROUP1, GROUP2, GROUP3, GROUP4, GROUP5],
    ignore_index=True
)

In [5]:
print(data.shape)
data.head()

(2395, 37)

,Unnamed: 0.1,Unnamed: 0,food,Caloric Value,Fat,Saturated Fats,Monounsaturated Fats,Polyunsaturated Fats,Carbohydrates,Sugars,...,Calcium,Copper,Iron,Magnesium,Manganese,Phosphorus,Potassium,Selenium,Zinc,Nutrition Density
0,0,0,cream cheese,51,5.0,2.9,1.3,0.200,0.8,0.500,...,0.008,14.100,0.082,0.027,1.300,0.091,15.5,19.100,0.039,7.070
1,1,1,neufchatel cheese,215,19.4,10.9,4.9,0.800,3.1,2.700,...,99.500,0.034,0.100,8.500,0.088,117.300,129.2,0.054,0.700,130.100
2,2,2,requeijao cremoso light catupiry,49,3.6,2.3,0.9,0.000,0.9,3.400,...,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.000,5.400
3,3,3,ricotta cheese,30,2.0,1.3,0.5,0.002,1.5,0.091,...,0.097,41.200,0.097,0.096,4.000,0.024,30.8,43.800,0.035,5.196
4,4,4,cream cheese low fat,30,2.3,1.4,0.6,0.042,1.2,0.900,...,22.200,0.072,0.008,1.200,0.098,22.800,37.1,0.034,0.053,27.007

In [6]:
data = data.fillna(0)

In [7]:
features = [
    "Caloric Value",
    "Fat",
    "Carbohydrates",
    "Sugars",
    "Protein",
    "Dietary Fiber",
    "Nutrition Density"
]

In [8]:
X = data[features]

In [9]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [10]:
from sklearn.neighbors import NearestNeighbors

model = NearestNeighbors(n_neighbors=5)

model.fit(X_scaled)

NearestNeighbors()

In [11]:
def recommend_food(food_name):
    
    food_index = data[data["food"] == food_name].index[0]
    
    distances, indices = model.kneighbors(
        [X_scaled[food_index]]
    )
    
    recommendations = data.iloc[indices[0]]["food"]
    
    return recommendations

In [12]:
recommend_food("apple butter")

41           apple butter
995             jackfruit
961     pineapples canned
962    prune plums canned
763              caramels
Name: food, dtype: object

In [13]:
high_risk_foods = data[
    (data["Caloric Value"] < 400) &
    (data["Sugars"] < 10) &
    (data["Saturated Fats"] < 5)
]

In [14]:
medium_risk_foods = data[
    (data["Caloric Value"] < 600) &
    (data["Sugars"] < 20)
]

In [15]:
low_risk_foods = data[
    (data["Nutrition Density"] > 70)
]

In [16]:
high_protein_foods = data[
    data["Protein"] > 15
]

In [17]:
low_sugar_foods = data[
    data["Sugars"] < 5
]

In [18]:
low_fat_foods = data[
    data["Fat"] < 10
]

In [19]:
high_fiber_foods = data[
    data["Dietary Fiber"] > 5
]

In [20]:
low_sodium_foods = data[
    data["Sodium"] < 200
]

In [21]:
risk = "High"
goal = "Weight Loss"

In [22]:
filtered_foods = data[
    (data["Sugars"] < 10) &
    (data["Fat"] < 10)
]

In [23]:
high_risk_foods.head()

,Unnamed: 0.1,Unnamed: 0,food,Caloric Value,Fat,Saturated Fats,Monounsaturated Fats,Polyunsaturated Fats,Carbohydrates,Sugars,...,Calcium,Copper,Iron,Magnesium,Manganese,Phosphorus,Potassium,Selenium,Zinc,Nutrition Density
0,0,0,cream cheese,51,5.0,2.9,1.300,0.200,0.8,0.500,...,0.008,14.100,0.082,0.027,1.300,0.091,15.5,19.100,0.039,7.070
2,2,2,requeijao cremoso light catupiry,49,3.6,2.3,0.900,0.000,0.9,3.400,...,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.000,5.400
3,3,3,ricotta cheese,30,2.0,1.3,0.500,0.002,1.5,0.091,...,0.097,41.200,0.097,0.096,4.000,0.024,30.8,43.800,0.035,5.196
4,4,4,cream cheese low fat,30,2.3,1.4,0.600,0.042,1.2,0.900,...,22.200,0.072,0.008,1.200,0.098,22.800,37.1,0.034,0.053,27.007
5,5,5,cream cheese fat free,19,0.2,0.1,0.091,0.075,1.4,1.000,...,63.200,0.039,0.053,4.000,0.028,94.100,50.0,0.013,0.300,67.679

In [24]:
print(high_risk_foods["Sugars"].max())
print(high_risk_foods["Fat"].max())

9.9
25.4

In [25]:
print(high_risk_foods.shape)

(1671, 37)

In [26]:
print("Original:", data.shape)
print("Filtered:", high_risk_foods.shape)

Original: (2395, 37)
Filtered: (1671, 37)

In [27]:
weight_loss_foods = data[
    (data["Caloric Value"] < 400) &
    (data["Sugars"] < 10) &
    (data["Fat"] < 10) &
    (data["Protein"] > 5)
]

In [28]:
weight_loss_foods.head()

,Unnamed: 0.1,Unnamed: 0,food,Caloric Value,Fat,Saturated Fats,Monounsaturated Fats,Polyunsaturated Fats,Carbohydrates,Sugars,...,Calcium,Copper,Iron,Magnesium,Manganese,Phosphorus,Potassium,Selenium,Zinc,Nutrition Density
6,6,6,gruyere cheese,116,9.1,5.3,2.8,0.5,0.1,0.100,...,283.1,0.033,0.094,10.1,0.002,169.4,22.7,0.079,1.1,300.694
7,7,7,cheddar cheese,113,9.3,5.3,2.6,0.3,0.9,0.100,...,198.8,0.099,0.077,7.6,0.063,127.4,21.3,0.009,1.0,215.530
8,8,8,parmesan cheese,71,4.5,2.7,1.4,0.1,0.6,0.046,...,213.1,0.051,0.100,7.9,0.073,124.9,16.6,0.045,0.5,224.777
12,12,12,swiss cheese,98,7.7,4.6,2.0,0.3,0.4,0.000,...,222.5,0.026,0.024,8.3,0.062,143.5,18.0,0.031,1.1,237.396
14,14,14,gouda cheese,100,7.7,4.9,2.2,0.2,0.6,0.600,...,196.0,0.013,0.060,8.1,0.080,152.9,33.9,0.050,1.1,211.424

In [29]:
high_risk = data[
    (data["Sugars"] < 10)
]

In [30]:
muscle_gain = data[
    (data["Protein"] > 20)
]

In [31]:
user = {
    "obesity_risk": "High",
    "goal": "Weight Loss"
}

In [32]:
if user["obesity_risk"] == "High":

    filtered_data = data[
        (data["Sugars"] < 10) &
        (data["Fat"] < 10)
    ]

elif user["obesity_risk"] == "Medium":

    filtered_data = data[
        (data["Sugars"] < 20)
    ]

else:

    filtered_data = data

In [33]:
features = [
    "Caloric Value",
    "Fat",
    "Carbohydrates",
    "Sugars",
    "Protein",
    "Dietary Fiber",
    "Nutrition Density"
]

X = filtered_data[features]

In [34]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

In [35]:
from sklearn.neighbors import NearestNeighbors

model = NearestNeighbors(n_neighbors=5)

model.fit(X_scaled)

NearestNeighbors()

In [36]:
def recommend_food(food_name):

    food_index = filtered_data[
        filtered_data["food"] == food_name
    ].index[0]

    filtered_position = list(filtered_data.index).index(food_index)

    distances, indices = model.kneighbors(
        [X_scaled[filtered_position]]
    )

    recommendations = filtered_data.iloc[
        indices[0]
    ][["food", "Caloric Value", "Protein", "Sugars"]]

    return recommendations

In [37]:
recommend_food("apple butter")

                  food  Caloric Value  Protein  Sugars
41        apple butter             35    0.045     7.1
894        prune puree             46    0.400     7.0
961  pineapples canned             28    0.200     6.8
995          jackfruit             33    0.600     6.7
887         clementine             35    0.600     6.8

In [38]:
foods_to_avoid = data[
    (data["Sugars"] > 20) |
    (data["Fat"] > 20)
]

In [39]:
print(data["Sugars"].max())
print(data["Fat"].max())

291.5
550.7

In [40]:
print(data["Sugars"].dtype)
print(data["Fat"].dtype)

float64
float64

In [41]:
data["Sugars"] = pd.to_numeric(
    data["Sugars"],
    errors="coerce"
)

data["Fat"] = pd.to_numeric(
    data["Fat"],
    errors="coerce"
)

In [42]:
foods_to_avoid = data[
    (data["Sugars"] > 20) |
    (data["Fat"] > 20)
]

In [43]:
foods_to_avoid.head()

,Unnamed: 0.1,Unnamed: 0,food,Caloric Value,Fat,Saturated Fats,Monounsaturated Fats,Polyunsaturated Fats,Carbohydrates,Sugars,...,Calcium,Copper,Iron,Magnesium,Manganese,Phosphorus,Potassium,Selenium,Zinc,Nutrition Density
11,11,11,port salut cheese,465,37.2,22.0,12.3,1.0,0.8,0.8,...,858.0,0.062,0.6,31.7,0.095,475.2,179.5,0.015,3.4,928.400
17,17,17,gjetost cheese,1058,67.0,43.5,17.9,2.1,96.8,0.0,...,908.0,0.200,1.2,158.9,0.035,1007.9,3198.4,0.039,2.6,1095.700
21,21,21,asadero cheese,402,31.9,20.3,9.1,1.0,3.2,3.2,...,746.9,0.067,0.6,29.4,0.024,500.6,97.2,0.096,3.4,808.175
24,24,24,roquefort cheese,314,26.0,16.4,7.2,1.1,1.7,0.0,...,562.7,0.005,0.5,25.5,0.036,333.2,77.4,0.081,1.8,609.400
25,25,25,queso blanco cheese,366,28.7,16.1,7.6,1.4,3.0,2.1,...,814.2,0.098,0.2,34.2,0.067,551.1,148.7,0.016,3.6,870.300

In [44]:
foods_to_avoid = data[
    (data["Sugars"] > 20) |
    (data["Fat"] > 20)
]

foods_to_avoid.head()

,Unnamed: 0.1,Unnamed: 0,food,Caloric Value,Fat,Saturated Fats,Monounsaturated Fats,Polyunsaturated Fats,Carbohydrates,Sugars,...,Calcium,Copper,Iron,Magnesium,Manganese,Phosphorus,Potassium,Selenium,Zinc,Nutrition Density
11,11,11,port salut cheese,465,37.2,22.0,12.3,1.0,0.8,0.8,...,858.0,0.062,0.6,31.7,0.095,475.2,179.5,0.015,3.4,928.400
17,17,17,gjetost cheese,1058,67.0,43.5,17.9,2.1,96.8,0.0,...,908.0,0.200,1.2,158.9,0.035,1007.9,3198.4,0.039,2.6,1095.700
21,21,21,asadero cheese,402,31.9,20.3,9.1,1.0,3.2,3.2,...,746.9,0.067,0.6,29.4,0.024,500.6,97.2,0.096,3.4,808.175
24,24,24,roquefort cheese,314,26.0,16.4,7.2,1.1,1.7,0.0,...,562.7,0.005,0.5,25.5,0.036,333.2,77.4,0.081,1.8,609.400
25,25,25,queso blanco cheese,366,28.7,16.1,7.6,1.4,3.0,2.1,...,814.2,0.098,0.2,34.2,0.067,551.1,148.7,0.016,3.6,870.300

In [45]:
print(foods_to_avoid.shape)

(396, 37)

In [46]:
foods_to_avoid

,Unnamed: 0.1,Unnamed: 0,food,Caloric Value,Fat,Saturated Fats,Monounsaturated Fats,Polyunsaturated Fats,Carbohydrates,Sugars,...,Calcium,Copper,Iron,Magnesium,Manganese,Phosphorus,Potassium,Selenium,Zinc,Nutrition Density
11,11,11,port salut cheese,465,37.2,22.0,12.3,1.0,0.8,0.8,...,858.0,0.062,0.600,31.7,0.095,475.2,179.5,0.015,3.4,928.400
17,17,17,gjetost cheese,1058,67.0,43.5,17.9,2.1,96.8,0.0,...,908.0,0.200,1.200,158.9,0.035,1007.9,3198.4,0.039,2.6,1095.700
21,21,21,asadero cheese,402,31.9,20.3,9.1,1.0,3.2,3.2,...,746.9,0.067,0.600,29.4,0.024,500.6,97.2,0.096,3.4,808.175
24,24,24,roquefort cheese,314,26.0,16.4,7.2,1.1,1.7,0.0,...,562.7,0.005,0.500,25.5,0.036,333.2,77.4,0.081,1.8,609.400
25,25,25,queso blanco cheese,366,28.7,16.1,7.6,1.4,3.0,2.1,...,814.2,0.098,0.200,34.2,0.067,551.1,148.7,0.016,3.6,870.300
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2365,692,692,potato salad,358,20.5,3.6,6.2,9.3,27.9,0.0,...,47.5,0.300,1.600,37.5,0.300,130.0,635.0,0.081,0.8,132.547
2366,693,693,taco salad taco bell,906,48.9,15.9,21.2,4.0,80.5,0.0,...,506.4,0.800,9.400,143.9,1.400,549.0,1220.6,0.095,6.2,696.900
2369,696,696,potato salad with egg,393,23.5,3.6,5.0,12.5,40.5,12.4,...,37.5,0.100,1.300,37.5,0.300,132.5,605.0,0.039,0.8,113.038
2372,699,699,grape apple salad with walnuts,191,8.2,1.1,1.4,5.3,25.6,20.3,...,70.1,0.200,0.500,27.7,0.300,97.8,264.1,0.016,0.6,119.357
2377,704,704,coleslaw,292,18.9,3.1,5.1,10.2,28.4,23.3,...,0.1,57.300,0.039,0.4,15.300,0.2,38.2,246.400,0.0,53.118

In [47]:
recommended_foods = data[
    ~data.index.isin(foods_to_avoid.index)
]

In [48]:
print(recommended_foods.shape)

(1999, 37)

In [49]:
features = [
    "Caloric Value",
    "Fat",
    "Carbohydrates",
    "Sugars",
    "Protein",
    "Dietary Fiber",
    "Nutrition Density"
]

X = recommended_foods[features]

In [50]:
X = X.apply(pd.to_numeric, errors='coerce')
X = X.fillna(0)

In [51]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

In [52]:
from sklearn.neighbors import NearestNeighbors

model = NearestNeighbors(n_neighbors=5)

model.fit(X_scaled)

NearestNeighbors()

In [53]:
def recommend_food(food_name):

    food_index = recommended_foods[
        recommended_foods["food"] == food_name
    ].index[0]

    filtered_position = list(
        recommended_foods.index
    ).index(food_index)

    distances, indices = model.kneighbors(
        [X_scaled[filtered_position]]
    )

    recommendations = recommended_foods.iloc[
        indices[0]
    ][
        ["food", "Caloric Value", "Protein", "Sugars"]
    ]

    return recommendations

In [54]:
recommend_food("apple butter")

                   food  Caloric Value  Protein  Sugars
41         apple butter             35    0.045     7.1
961   pineapples canned             28    0.200     6.8
995           jackfruit             33    0.600     6.7
894         prune puree             46    0.400     7.0
962  prune plums canned             27    0.200     6.5

In [55]:
print("Recommended because:")
print("- Low sugar")
print("- Low fat")
print("- Suitable for obesity management")

Recommended because:
- Low sugar
- Low fat
- Suitable for obesity management

In [56]:
user = {
    "obesity_risk": "High"
}

In [57]:
user = {
    "obesity_risk": "Medium"
}

In [58]:
goal = "High Protein"

In [59]:
features = [
    "Caloric Value",
    "Fat",
    "Carbohydrates",
    "Sugars",
    "Protein",
    "Dietary Fiber",
    "Nutrition Density"
]

In [60]:
X = recommended_foods[features]

X = X.apply(pd.to_numeric, errors='coerce')

X = X.fillna(0)

In [61]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

In [62]:
from sklearn.neighbors import NearestNeighbors

model = NearestNeighbors(
    n_neighbors=5,
    metric='euclidean'
)

model.fit(X_scaled)

NearestNeighbors(metric='euclidean')

In [63]:
def recommend_food(food_name):

    food_index = recommended_foods[
        recommended_foods["food"] == food_name
    ].index[0]

    filtered_position = list(
        recommended_foods.index
    ).index(food_index)

    distances, indices = model.kneighbors(
        [X_scaled[filtered_position]]
    )

    recommendations = recommended_foods.iloc[
        indices[0]
    ][
        ["food", "Protein", "Sugars", "Fat"]
    ]

    return recommendations

In [64]:
recommend_food("apple butter")

                   food  Protein  Sugars    Fat
41         apple butter    0.045     7.1  0.063
961   pineapples canned    0.200     6.8  0.050
995           jackfruit    0.600     6.7  0.200
894         prune puree    0.400     7.0  0.020
962  prune plums canned    0.200     6.5  0.075

In [65]:
recommend_food("cream cheese")

                       food  Protein  Sugars  Fat
0              cream cheese      0.9     0.5  5.0
1972  bacon tomato dressing      0.3     0.3  5.3
1699             turkey fat      0.0     0.0  5.0
1703          mutton tallow      0.0     0.0  5.0
1701              goose fat      0.0     0.0  5.0

In [66]:
recommend_food("swiss cheese")

               food  Protein  Sugars  Fat
12     swiss cheese      6.7     0.0  7.7
864     edam cheese      7.5     0.0  8.3
14     gouda cheese      7.0     0.6  7.7
16   caraway cheese      7.1     0.0  8.3
20     brick cheese      7.0     0.2  8.9

In [67]:
def recommend_food(food_name):

    food_index = recommended_foods[
        recommended_foods["food"] == food_name
    ].index[0]

    filtered_position = list(
        recommended_foods.index
    ).index(food_index)

    distances, indices = model.kneighbors(
        [X_scaled[filtered_position]]
    )

    recommendations = recommended_foods.iloc[
        indices[0]
    ][
        ["food", "Protein", "Sugars", "Fat"]
    ]

    recommendations = recommendations.drop_duplicates(
        subset="food"
    )

    recommendations = recommendations[
        recommendations["food"] != food_name
    ]

    return recommendations

In [68]:
data = data.drop_duplicates()

data = data.fillna(0)

In [69]:
numeric_columns = [
    "Caloric Value",
    "Fat",
    "Sugars",
    "Protein",
    "Dietary Fiber",
    "Carbohydrates",
    "Nutrition Density"
]

for col in numeric_columns:
    data[col] = pd.to_numeric(
        data[col],
        errors='coerce'
    )

data = data.fillna(0)

In [70]:
high_risk_foods = data[
    (data["Sugars"] < 10) &
    (data["Fat"] < 10) &
    (data["Caloric Value"] < 400)
]

In [71]:
moderate_risk_foods = data[
    (data["Sugars"] < 15) &
    (data["Fat"] < 15)
]

In [72]:
low_risk_foods = data[
    (data["Nutrition Density"] > 0.5)
]

In [73]:
weight_loss_foods = data[
    (data["Caloric Value"] < 350) &
    (data["Sugars"] < 10) &
    (data["Fat"] < 10)
]

In [74]:
muscle_gain_foods = data[
    (data["Protein"] > 15)
]

In [75]:
maintenance_foods = data[
    (data["Nutrition Density"] > 0.5) &
    (data["Sugars"] < 15)
]

In [76]:
recommended_foods = high_risk_foods.copy()

In [77]:
features = [
    "Caloric Value",
    "Fat",
    "Carbohydrates",
    "Sugars",
    "Protein",
    "Dietary Fiber",
    "Nutrition Density"
]

X = recommended_foods[features]

In [78]:
X = X.fillna(0)

In [79]:
scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

In [80]:
model = NearestNeighbors(
    n_neighbors=5,
    metric='euclidean'
)

model.fit(X_scaled)

print("KNN Recommendation Model Trained Successfully!")

KNN Recommendation Model Trained Successfully!

In [81]:
def recommend_food(food_name):

    try:

        # FIND FOOD INDEX
        food_index = recommended_foods[
            recommended_foods["food"] == food_name
        ].index[0]

        # GET POSITION
        filtered_position = list(
            recommended_foods.index
        ).index(food_index)

        # FIND SIMILAR FOODS
        distances, indices = model.kneighbors(
            [X_scaled[filtered_position]]
        )

        # GET RECOMMENDATIONS
        recommendations = recommended_foods.iloc[
            indices[0]
        ][
            [
                "food",
                "Caloric Value",
                "Protein",
                "Sugars",
                "Fat",
                "Nutrition Density"
            ]
        ]

        # REMOVE DUPLICATES
        recommendations = recommendations.drop_duplicates(
            subset="food"
        )

        # REMOVE INPUT FOOD
        recommendations = recommendations[
            recommendations["food"] != food_name
        ]

        return recommendations

    except:
        print("Food not found!")

In [82]:
def explain_food(food):

    selected = recommended_foods[
        recommended_foods["food"] == food
    ]

    if len(selected) == 0:
        print("Food not found!")
        return

    print("\nRecommended because:\n")

    if selected["Sugars"].values[0] < 10:
        print("- Low sugar")

    if selected["Fat"].values[0] < 10:
        print("- Low fat")

    if selected["Protein"].values[0] > 15:
        print("- High protein")

    if selected["Nutrition Density"].values[0] > 0.5:
        print("- High nutrition density")

In [83]:
def get_daily_calories(activity_level):

    if activity_level == "Sedentary":
        return 1800

    elif activity_level == "Moderately Active":
        return 2200

    elif activity_level == "Highly Active":
        return 2800

    else:
        return 2000

In [84]:
import pickle

pickle.dump(
    model,
    open("diet_model.pkl", "wb")
)

In [85]:
pickle.dump(
    model,
    open("diet_recommendation_model.pkl", "wb")
)

pickle.dump(
    scaler,
    open("diet_scaler.pkl", "wb")
)

print("\nModel and scaler saved successfully!")

Model and scaler saved successfully!

In [86]:
print("FOOD RECOMMENDATION TEST")
print("==============================\n")

food_name = "apple butter"

print(f"Input Food: {food_name}\n")

recommendations = recommend_food(food_name)

print(recommendations)

print("\n==============================")

explain_food(food_name)

print("\n==============================")

activity_level = "Moderately Active"

calories = get_daily_calories(activity_level)

print(f"\nDaily Calories: {calories} kcal")

FOOD RECOMMENDATION TEST
==============================

Input Food: apple butter

                   food  Caloric Value  Protein  Sugars    Fat  \
961   pineapples canned             28      0.2     6.8  0.050
995           jackfruit             33      0.6     6.7  0.200
894         prune puree             46      0.4     7.0  0.020
962  prune plums canned             27      0.2     6.5  0.075

     Nutrition Density
961             19.255
995              9.574
894             12.709
962             13.728

==============================

Recommended because:

- Low sugar
- Low fat
- High nutrition density

==============================

Daily Calories: 2200 kcal